### ISSUE TITLE
Stopped working anymore

### ISSUE THREAD

**Issue by velam2019** [vofik/Kink.bundle#14]
Seemed to stop working about a week ago so now it finds the studio but will not get he name, cast or any other of the information.

**Comment by hkghgkhbnvt** [comment]
change line 64 from

`metadata.title = html.xpath('//div[@class="shoot-info"]//h1/text()')[0] + " (" + metadata.id + ")"`

to 

`metadata.title = html.xpath('//h1[@class="shoot-title"]/text()')[0] + " (" + metadata.id + ")"`

Use spaces not tabs for intendation

**Comment by velam2019** [comment]
Thank you, Your the solution worked!
